name = "arthaflow"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "arthaflow-db"
database_id = "44e8b848-e8b1-48b2-a550-848a2862f47c"
